[package]
name = "amudai-scratchpad"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
amudai-bits = { workspace = true }
amudai-bytes = { workspace = true }
amudai-page-alloc = { workspace = true }
amudai-position-set = { workspace = true }
amudai-ranges = { workspace = true }
amudai-workflow = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
fastrand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
