[package]
name = "amudai-bytes"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
amudai-common-traits = { workspace = true }
bytemuck = { workspace = true }
