[package]
name = "amudai-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
planus = { workspace = true }
thiserror = { workspace = true }
