[package]
name = "arrow-processing"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-cast = { workspace = true }
arrow-data = { workspace = true }
arrow-json = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
fastrand = { workspace = true }
half = { workspace = true }
