[package]
name = "arrow-builders"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-schema = { workspace = true }

arrow-builders-macros = { workspace = true }

[dev-dependencies]
arrow-processing = { workspace = true }
