[package]
name = "amudai-ranges"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
amudai-shared-vec = { workspace = true }
